set CodeLiteDir=C:\Program Files\CodeLite
set WXWIN32=gcc510TDMDev_dll
set WXWIN64=gcc_dllx86_64
set WXWIN=C:\wxWidgets-3.1.1
set WXCFG=$WXWIN64/mswu
set GLEW_INCLUDE=C:\SDK\glew-2.1.0\include
set GLEWBIN32=C:\SDK\glew-2.1.0\bin\Release\Win32
set GLEWBIN64=C:\SDK\glew-2.1.0\bin\Release\x64
set GLEWLIB32=/SDK/glew-2.1.0/lib/Release/Win32
set GLEWLIB64=/SDK/glew-2.1.0/lib/Release/x64
set GLM_INCLUDE=C:\SDK\glm
set OPENCL_INCLUDE=C:\SDK\OpenCL-Headers\opencl22
set OPENCL_LIB64=C:\SDK\OpenCL
set OPENCL_LIB32=C:\Program Files (x86)\AMD APP SDK\3.0\lib\x86
set PATH=%WXWIN%\lib\%WXWIN64%;%GLEWBIN64%;%SystemRoot%;%SystemRoot%\System32;%CodeLiteDir%;C:\Program Files\SlikSvn\bin
