name: CI-ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: ['.github/workflows/ubuntu.yaml','**/CMakeLists.txt', '**/Makefile', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp', '**/*.cl', '**/*.cs', '**/*.sln', '**/*.csproj', '**/appsettings.json']
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['.github/workflows/ubuntu.yaml', '**/CMakeLists.txt', '**/Makefile', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp', '**/*.cl', '**/*.cs', '**/*.sln', '**/*.csproj', '**/appsettings.json']

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
    - name: Install OpenCLSolarSystem dependencies
      run: |
        sudo apt update
        sudo apt install build-essential git cmake ninja-build libgl1-mesa-dev libglew-dev opencl-headers ocl-icd-opencl-dev libwxgtk3.2-dev

    - name: Checkout OpenCLSolarSystem
      uses: actions/checkout@v4
      with:
        path: openclsolarsystem
        fetch-depth: 0

    - name: Build OpenCLSolarSystem
      run: |
        cd openclsolarsystem
        cmake -B build -S src/OpenCLSolarSystem -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -j$(nproc)

    - name: Setup dotnet 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'

    - name: Build OrbToSlf using dotnet
      run: |
        cd openclsolarsystem/src/OrbToSlf
        # Build main projects to a specific output directory
        dotnet publish OrbToSlfConsole/OrbToSlfConsole.csproj --configuration Release --framework net8.0 --output ./OrbToSlfConsole/bin/Release/publish
        # Build and run tests with coverage
        dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory:"./OrbToSlfConsole/bin/Release/TestResults" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover
